### ISSUE TITLE
concurrent map write

### ISSUE THREAD

**Issue by ws6** [ws6/msi#1]
fatal error: concurrent map writes

goroutine 30 [running]:
runtime.throw(0xa5bc51, 0x15)
        C:/Go/src/runtime/panic.go:596 +0x9c fp=0xc04240fb18 sp=0xc04240faf8
runtime.mapassign(0x9b0e00, 0xc042127440, 0xc04240fc48, 0x2)
        C:/Go/src/runtime/hashmap.go:499 +0x66e fp=0xc04240fbb8 sp=0xc04240fb18
github.com/ws6/msi.(*Msi).installForeignKeyMap(0xc042054f80)
        C:/Users/jliu1/GolangProjects/src/github.com/ws6/msi/tabledb.go:723 +0x1f6 fp=0xc04240fc88 sp=0xc04240fbb8
github.com/ws6/msi.(*Msi).Map(0xc042054f80, 0xc04212e320, 0xc0423f64e0, 0x18f, 0xc0423b60c0, 0x0, 0x0, 0x0, 0x0, 0x0
        C:/Users/jliu1/GolangProjects/src/github.com/ws6/msi/tabledb.go:735 +0x8cf fp=0xc04240fda0 sp=0xc04240fc88
github.com/ws6/msi.(*Stmt).Map(0xc0422e80f0, 0x0, 0x0, 0x0, 0xc04213a518, 0x0, 0x0, 0x0, 0x0)
        C:/Users/jliu1/GolangProjects/src/github.com/ws6/msi/tabledb.go:481 +0x293 fp=0xc04240fef0 sp=0xc04240fda0
github.com/ws6/msi.(*Stmt).Chan.func1(0xc0422e80f0, 0xc04203a300, 0x3e8)
        C:/Users/jliu1/GolangProjects/src/github.com/ws6/msi/tabledb.go:223 +0x10b fp=0xc04240ffc8 sp=0xc04240fef0
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc04240ffd0 sp=0xc04240ffc8
created by github.com/ws6/msi.(*Stmt).Chan
        C:/Users/jliu1/GolangProjects/src/github.com/ws6/msi/tabledb.go:243 +0x370

goroutine 1 [chan receive]:
github.com/astaxie/beego.(*App).Run(0xc04203ded0)
        C:/Users/jliu1/GolangProjects/src/github.com/astaxie/beego/app.go:186 +0x59e
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
        C:/Users/jliu1/GolangProjects/src/github.com/astaxie/beego/beego.go:67 +0x58
main.main()
        C:/Users/jliu1/GolangProjects/src/git.illumina.com/Operations/recook/main.go:29 +0x185

**Comment by ws6** [comment]
seems gone.
